replicaCount: 1

image:
  repository: flask-metrics-app
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  host: flask.local

config:
  appEnv: production
  logLevel: info

secret:
  apiKey: test-api-key

otel:
  serviceName: flask-metrics-app
  tracesEndpoint: http://tempo.default.svc.cluster.local:4318/v1/traces

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
