apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: flask-metrics-app:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: APP_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: LOG_LEVEL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: API_KEY
            - name: OTEL_SERVICE_NAME
              value: "flask-metrics-app"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://tempo:4318/v1/traces"
